### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cachedir'

### ISSUE THREAD

**Issue by orkhan-amrullayev** [MaartenGr/Concept#16]
I was reproducing the same Colab notebook in the ReadME without any change:
https://colab.research.google.com/drive/1XHwQPT2itZXu1HayvGoj60-xAXxg9mqe?usp=sharing#scrollTo=VcgGxrLH-AU9

While importing the library `from concept import ConceptModel`, this error appears:

TypeError: __init__() got an unexpected keyword argument 'cachedir'

Apparently it stems from hdbscan module as cachedir was removed from joblib.Memory.
https://github.com/joblib/joblib/blame/3fb7fbde772e10415f879e0cb7e5d986fede8460/joblib/memory.py#L910

**Comment by MaartenGr** [comment]
There are a few solutions [here](https://github.com/MaartenGr/BERTopic/issues/770) and [here](https://github.com/MaartenGr/BERTopic/issues/730) you can try as BERTopic is having the same issue since HDBSCAN is a dependency there as well.
