### ISSUE TITLE
Saving the model

### ISSUE THREAD

**Issue by vvkishere** [MaartenGr/Concept#8]
Hi.

Thank you very much for creating this. It is an absolutely brilliant idea. Once we have created the model, how do we save the model and use it for any new data that comes in?

**Comment by MaartenGr** [comment]
You can save the model using `.save(path="my_model")`. That way, you can save the model and load it with `ConceptModel.load(path="my_model")`  to use it for new data.

**Comment by vvkishere** [comment]
perfect. Thank you.
