### ISSUE TITLE
Using GPU while processing concepts

### ISSUE THREAD

**Issue by vvkishere** [MaartenGr/Concept#9]
Any plans on supporting GPU processing for this to speed up the model creation?

**Comment by MaartenGr** [comment]
Currently, GPU is only supported for generating multi-modal embeddings. This is typically the most computation-heavy task in Concept. As of right now, there are no plans on supporting GPU processing for HDBSCAN and UMAP.

**Comment by vvkishere** [comment]
Thank you.
